### ISSUE TITLE
how to install async-ext

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [swoole/ext-async#2]
is it possible to be installed with PECL?

**Comment by kency** [comment]
or yum?

**Comment by MarkGor** [comment]
3026  2019-04-23 16:15:17 cd /usr/src/
 3027  2019-04-23 16:15:19 wget https://github.com/swoole/ext-async/archive/4.3.2.tar.gz
 3028  2019-04-23 16:15:59 mv 4.3.2.tar.gz async-ext.tar.gz
 3029  2019-04-23 16:16:05 tar -zxvf async-ext.tar.gz 
 3030  2019-04-23 16:16:08 cd ext-async-4.3.2/
 3031  2019-04-23 16:16:11 phpize 
 3032  2019-04-23 16:16:21 ./configure 
 3033  2019-04-23 16:16:29 make
 3034  2019-04-23 16:16:45 make install
 3036  2019-04-23 16:17:38 php --ini
 3038  2019-04-23 16:18:23 vi /usr/local/php-7.2.12/lib/php.ini <---add  swoole_async.so to php.ini

[root@master ext-async-4.3.2]# php -m|grep async
swoole_async

**Comment by mariuszkrzaczkowski** [comment]
why can not you give it to pecl or yum?
it would be much easier
e.g. pecl install swoole_async

**Comment by pervozdanniy** [comment]
in docker:
`#install swoole async ext
RUN cd /tmp && \
    git clone https://github.com/swoole/async-ext.git && cd async-ext && \
    git checkout tags/v4.3.3 && \
    ./make.sh && \
    docker-php-ext-enable swoole_async && \
    rm -rf /tmp/*`

**Comment by MaryMeteor** [comment]
I cant install this ext on stage "make"

> [root@www async-ext]# make
> /bin/sh /tmp/async-ext/libtool --mode=compile g++  -I. -I/tmp/async-ext -DPHP_ATOM_INC -I/tmp/async-ext/include -I/tmp/async-ext/main -I/tmp/async-ext -I/opt/remi/php73/root/usr/include/php -I/opt/remi/php73/root/usr/include/php/main -I/opt/remi/php73/root/usr/include/php/TSRM -I/opt/remi/php73/root/usr/include/php/Zend -I/opt/remi/php73/root/usr/include/php/ext -I/opt/remi/php73/root/usr/include/php/ext/date/lib -I/tmp/async-ext -I/tmp/async-ext/include -I/opt/remi/php73/root/usr/include/php/ext/swoole -I/opt/remi/php73/root/usr/include/php/ext/swoole/include  -DHAVE_CONFIG_H  -g -O2 -Wall -Wno-unused-function -Wno-deprecated -Wno-deprecated-declarations -std=c++11   -c /tmp/async-ext/swoole_async.cc -o swoole_async.lo
> libtool: compile:  g++ -I. -I/tmp/async-ext -DPHP_ATOM_INC -I/tmp/async-ext/include -I/tmp/async-ext/main -I/tmp/async-ext -I/opt/remi/php73/root/usr/include/php -I/opt/remi/php73/root/usr/include/php/main -I/opt/remi/php73/root/usr/include/php/TSRM -I/opt/remi/php73/root/usr/include/php/Zend -I/opt/remi/php73/root/usr/include/php/ext -I/opt/remi/php73/root/usr/include/php/ext/date/lib -I/tmp/async-ext -I/tmp/async-ext/include -I/opt/remi/php73/root/usr/include/php/ext/swoole -I/opt/remi/php73/root/usr/include/php/ext/swoole/include -DHAVE_CONFIG_H -g -O2 -Wall -Wno-unused-function -Wno-deprecated -Wno-deprecated-declarations -std=c++11 -c /tmp/async-ext/swoole_async.cc  -fPIC -DPIC -o .libs/swoole_async.o
> In file included from /tmp/async-ext/swoole_async.cc:17:0:
> /tmp/async-ext/php_swoole_async.h:26:35: fatal error: ext/swoole/php_swoole.h: No such file or directory
>  #include "ext/swoole/php_swoole.h"
>                                    ^
> compilation terminated.
> make: *** [swoole_async.lo] Error 1

its work on php73 ?

**Comment by doubaokun** [comment]
@MaryMeteor this extension depends on the swoole extension.

**Comment by scil** [comment]
> 
> 
> @MaryMeteor this extension depends on the swoole extension.

How can I add this depend dependency? I have install swoole ext by pecl, but encounter this error too.

**Comment by francescozanoni** [comment]
@MaryMeteor I had the same issue when I installed Swoole from PECL and ext-async from source: by installing both from source, no issue.

See my other answer here: https://github.com/swoole/ext-async/issues/3#issuecomment-511132318

Hope this helps!

**Comment by nicoren-te** [comment]
@francescozanoni : Thank you. I will try this.

**Comment by deminy** [comment]
Besides what @francescozanoni had suggested, you may also check the suggestions I left [here](https://github.com/swoole/ext-async/issues/3#issuecomment-524732456) about installing Swoole extensions and use [the official Swoole image](https://hub.docker.com/r/phpswoole/swoole).
