### ISSUE TITLE
error: ‘swoole_version_id’ was not declared in this scope

### ISSUE THREAD

**Issue by T200proX7** [swoole/ext-async#21]
> /root/async-ext/swoole_async.cc: In function ‘int zm_startup_swoole_async(int, int)’:
/root/async-ext/swoole_async.cc:1708:62: error: ‘swoole_version_id’ was not declared in this scope
     if (PHP_SWOOLE_EXT_ASYNC_VERSION_ID != swoole_version_id())
                                                              ^
Makefile:194: recipe for target 'swoole_async.lo' failed

i just tried to compile swoole_async but its not working due the swoole_version_id() function does not exist.

**Comment by twose** [comment]
Please use the same version with Swoole, thanks
