### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ermya** [swoole/ext-async#24]
i can not install async-ext on swoole 
is there any hint , i just install swoole last version from git
i try to install async-ext but face me error when i enter make -j 4

`/downloads/async-ext/php_swoole_async.h:35:2: error: #error "Ext version does not match the Swoole version"
 #error "Ext version does not match the Swoole version"
  ^~~~~
In file included from /downloads/async-ext/swoole_async_client.cc:17:
/downloads/async-ext/php_swoole_async.h:35:2: error: #error "Ext version does not match the Swoole version"
 #error "Ext version does not match the Swoole version"
  ^~~~~
In file included from /downloads/async-ext/swoole_mysql_async.h:22,
                 from /downloads/async-ext/swoole_mysql.c:19:
/downloads/async-ext/php_swoole_async.h:35:2: error: #error "Ext version does not match the Swoole version"
 #error "Ext version does not match the Swoole version"
  ^~~~~
In file included from /downloads/async-ext/swoole_redis.c:17:
/downloads/async-ext/php_swoole_async.h:35:2: error: #error "Ext version does not match the Swoole version"
 #error "Ext version does not match the Swoole version"
  ^~~~~
make: *** [Makefile:198: swoole_redis.lo] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:196: swoole_mysql.lo] Error 1
make: *** [Makefile:194: swoole_async_client.lo] Error 1
make: *** [Makefile:192: swoole_async.lo] Error 1
`

is there any hint ?

**Comment by twose** [comment]
please read the error message
