### ISSUE TITLE
Compile from master fails with error ext/swoole/php_swoole.h: No such file or directory

### ISSUE THREAD

**Issue by GhaziTriki** [swoole/ext-async#3]
Doing `make -j 4` generated the following error.

```
/bin/bash /home/riadvice/async-ext/libtool --mode=compile g++  -I. -I/home/riadvice/async-ext -DPHP_ATOM_INC -I/home/riadvice/async-ext/include -I/home/riadvice/async-ext/main -I/home/riadvice/async-ext -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/home/riadvice/async-ext -I/home/riadvice/async-ext/include -I/usr/include/php/20180731/ext/swoole -I/usr/include/php/20180731/ext/swoole/include  -DHAVE_CONFIG_H  -g -O2 -Wall -Wno-unused-function -Wno-deprecated -Wno-deprecated-declarations -std=c++11   -c /home/riadvice/async-ext/swoole_async.cc -o swoole_async.lo
/bin/bash /home/riadvice/async-ext/libtool --mode=compile cc  -I. -I/home/riadvice/async-ext -DPHP_ATOM_INC -I/home/riadvice/async-ext/include -I/home/riadvice/async-ext/main -I/home/riadvice/async-ext -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/home/riadvice/async-ext -I/home/riadvice/async-ext/include -I/usr/include/php/20180731/ext/swoole -I/usr/include/php/20180731/ext/swoole/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /home/riadvice/async-ext/swoole_mysql.c -o swoole_mysql.lo
/bin/bash /home/riadvice/async-ext/libtool --mode=compile cc  -I. -I/home/riadvice/async-ext -DPHP_ATOM_INC -I/home/riadvice/async-ext/include -I/home/riadvice/async-ext/main -I/home/riadvice/async-ext -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/home/riadvice/async-ext -I/home/riadvice/async-ext/include -I/usr/include/php/20180731/ext/swoole -I/usr/include/php/20180731/ext/swoole/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /home/riadvice/async-ext/swoole_redis.c -o swoole_redis.lo
/bin/bash /home/riadvice/async-ext/libtool --mode=compile cc  -I. -I/home/riadvice/async-ext -DPHP_ATOM_INC -I/home/riadvice/async-ext/include -I/home/riadvice/async-ext/main -I/home/riadvice/async-ext -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/home/riadvice/async-ext -I/home/riadvice/async-ext/include -I/usr/include/php/20180731/ext/swoole -I/usr/include/php/20180731/ext/swoole/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /home/riadvice/async-ext/swoole_msgqueue.c -o swoole_msgqueue.lo
libtool: compile:  cc -I. -I/home/riadvice/async-ext -DPHP_ATOM_INC -I/home/riadvice/async-ext/include -I/home/riadvice/async-ext/main -I/home/riadvice/async-ext -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/home/riadvice/async-ext -I/home/riadvice/async-ext/include -I/usr/include/php/20180731/ext/swoole -I/usr/include/php/20180731/ext/swoole/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /home/riadvice/async-ext/swoole_redis.c  -fPIC -DPIC -o .libs/swoole_redis.o
In file included from /home/riadvice/async-ext/swoole_redis.c:17:0:
/home/riadvice/async-ext/php_swoole_async.h:26:35: fatal error: ext/swoole/php_swoole.h: No such file or directory
compilation terminated.
libtool: compile:  g++ -I. -I/home/riadvice/async-ext -DPHP_ATOM_INC -I/home/riadvice/async-ext/include -I/home/riadvice/async-ext/main -I/home/riadvice/async-ext -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/home/riadvice/async-ext -I/home/riadvice/async-ext/include -I/usr/include/php/20180731/ext/swoole -I/usr/include/php/20180731/ext/swoole/include -DHAVE_CONFIG_H -g -O2 -Wall -Wno-unused-function -Wno-deprecated -Wno-deprecated-declarations -std=c++11 -c /home/riadvice/async-ext/swoole_async.cc  -fPIC -DPIC -o .libs/swoole_async.o
libtool: compile:  cc -I. -I/home/riadvice/async-ext -DPHP_ATOM_INC -I/home/riadvice/async-ext/include -I/home/riadvice/async-ext/main -I/home/riadvice/async-ext -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/home/riadvice/async-ext -I/home/riadvice/async-ext/include -I/usr/include/php/20180731/ext/swoole -I/usr/include/php/20180731/ext/swoole/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /home/riadvice/async-ext/swoole_msgqueue.c  -fPIC -DPIC -o .libs/swoole_msgqueue.o
libtool: compile:  cc -I. -I/home/riadvice/async-ext -DPHP_ATOM_INC -I/home/riadvice/async-ext/include -I/home/riadvice/async-ext/main -I/home/riadvice/async-ext -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -I/home/riadvice/async-ext -I/home/riadvice/async-ext/include -I/usr/include/php/20180731/ext/swoole -I/usr/include/php/20180731/ext/swoole/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /home/riadvice/async-ext/swoole_mysql.c  -fPIC -DPIC -o .libs/swoole_mysql.o
/home/riadvice/async-ext/swoole_msgqueue.c:17:24: fatal error: php_swoole.h: No such file or directory
compilation terminated.
In file included from /home/riadvice/async-ext/swoole_async.cc:17:0:
/home/riadvice/async-ext/php_swoole_async.h:26:35: fatal error: ext/swoole/php_swoole.h: No such file or directory
compilation terminated.
In file included from /home/riadvice/async-ext/swoole_mysql.c:19:0:
/home/riadvice/async-ext/php_swoole_async.h:26:35: fatal error: ext/swoole/php_swoole.h: No such file or directory
compilation terminated.
Makefile:198: recipe for target 'swoole_redis.lo' failed
make: *** [swoole_redis.lo] Error 1
make: *** Waiting for unfinished jobs....
Makefile:194: recipe for target 'swoole_async.lo' failed
make: *** [swoole_async.lo] Error 1
Makefile:196: recipe for target 'swoole_mysql.lo' failed
make: *** [swoole_mysql.lo] Error 1
Makefile:200: recipe for target 'swoole_msgqueue.lo' failed
make: *** [swoole_msgqueue.lo] Error 1
```

**Comment by mansoncui** [comment]
Are you ready to solve it

**Comment by scil** [comment]
same error.

**Comment by nicoren-te** [comment]
+1

**Comment by francescozanoni** [comment]
My solution is by installing Swoole from source, not from PECL: this makes Swoole Async extension install (from source, of course) without issues.
I have PHP 7.2 on Ubuntu 18.04.
Hope this helps!

**Comment by DCapriCorn** [comment]
Have same error on make -j 4 stage, i have installed `swoole` extension already

**Comment by francescozanoni** [comment]
@DCapriCorn How did you install it? Via PECL or via source code? Via PECL seems to be incompatible with Swoole Async installation via source code.

**Comment by francescozanoni** [comment]
> Have same error on make -j 4 stage, i have installed `swoole` extension already

How did you install it? Via PECL or via source code? Via PECL seems to be incompatible with Swoole Async installation via source code.

**Comment by winslis2** [comment]
Make sure the two versions are consistent
and don't froget ./configure --with-php-config=..........
you can try try

**Comment by andrei-dascalu** [comment]
@winslis2 what do you mean by "make sure the two versions are consistent" ? Swoole has version 4.4.4 now but ext-async only goes to 4.4.3

**Comment by idekel** [comment]
Hi everyone,
I have this error too. I tried to install both extensions from source and got this other:
` error ext-async/swoole_async.cc:936:17: error: ‘struct swGlobal_t’ has no member named ‘main_reactor’
     if (SwooleG.main_reactor != NULL)`

**Comment by winslis2** [comment]
> @winslis2 what do you mean by "make sure the two versions are consistent" ? Swoole has version 4.4.4 now but ext-async only goes to 4.4.3

swoole version 4.4.4 has coroutines model，ext-async is Outdated

**Comment by deminy** [comment]
For now Swoole extensions (including the [async](https://github.com/swoole/ext-async) extension) are not tagged/released the same way as Swoole, thus it could be painful when using them with old versions of Swoole. Here is my suggestion to use or install the _async_ extension (and other Swoole extensions):

1. Use [the official Swoole image](https://hub.docker.com/r/phpswoole/swoole). It has most Swoole extensions installed, although some of them not enabled by default.

2. If you prefer to install a Swoole extension from source code, you may need to download the Git repository and switch to a Git commit first. You can find out which commit to use from the configuration files [here](https://github.com/swoole/docker-swoole/tree/master/config). For example,

* For Swoole 4.3.6 (and some older 4.3.x releases), use commit [e0f48077fe59e5d3194bc4215c1cafca39a093cf](https://github.com/swoole/docker-swoole/blob/master/config/4.3.6.yml#L14).
* For Swoole 4.4.4 (and some older 4.4.x releases), use commit [6df15d51f9edd9950c418f2374d0b97fce08a30b](https://github.com/swoole/docker-swoole/blob/master/config/4.4.4.yml#L14).

If you want to install with the latest code, please follow what @francescozanoni had suggested.

**Comment by andrei-dascalu** [comment]
@deminy thanks a lot!
Also, pretty nice that you maintain x64 and arm images per each php version 

Cheers!

**Comment by fakharak** [comment]
> > @winslis2 what do you mean by "make sure the two versions are consistent" ? Swoole has version 4.4.4 now but ext-async only goes to 4.4.3
> 
> swoole version 4.4.4 has coroutines model，ext-async is Outdated

I am using latest Swoole version 4.6.6. but this extension is confusing. My question is "can i make Asynchronous Client / Calls" in Swoole, without "ext-async" ? I mean is there an aleternate mechanism available ? to write Asynchrnous Client / Calls without "ext-async" ? OR, "ext-async" is one and only (mandatory) way in Swoole to write Asynchronous Client / Calls ?

**Comment by fakharak** [comment]
For some who have confusion about whether they should really use ext-async, or recommended swoole\coroutine\client for Swoole Asynchronous Clients / Calls.
https://github.com/swoole/ext-async/issues/40

> > > @winslis2 what do you mean by "make sure the two versions are consistent" ? Swoole has version 4.4.4 now but ext-async only goes to 4.4.3
> > 
> > 
> > swoole version 4.4.4 has coroutines model，ext-async is Outdated
> 
> I am using latest Swoole version 4.6.6. but this extension is confusing. My question is "can i make Asynchronous Client / Calls" in Swoole, without "ext-async" ? I mean is there an aleternate mechanism available ? to write Asynchrnous Client / Calls without "ext-async" ? OR, "ext-async" is one and only (mandatory) way in Swoole to write Asynchronous Client / Calls ?

https://github.com/swoole/ext-async/issues/40
