### ISSUE TITLE
difference between ext-async and mainline swoole

### ISSUE THREAD

**Issue by need-sleep** [swoole/ext-async#6]
What is the difference between this extension and the similar functions in swoole-ext? Other than missing features (coros for example) are the existing functions in this ext the same as in mainline swoole-ext?

**Comment by doubaokun** [comment]
Coroutine style API became the mainstream in the mainline Swoole since version 4.3.0.

Ext-async depends on Swoole core, it is the `extension` of mainline Swoole, including the async callback style API.

**Comment by need-sleep** [comment]
This answers a couple of questions for me. Thanks!
